apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf-cm
  namespace: deploy-uat
data:
  nginx.conf: |
    user nginx;
    worker_processes  1;
    error_log  /dev/stdout;
    events {
      worker_connections  10240;
    }
    http {

      access_log  /dev/stdout;
      server {

        listen 443 ssl;

        ssl_certificate /etc/ssl/digicorpuatin.crt;
        ssl_certificate_key /etc/ssl/digicorpuatin.key;

        server_name digicorpuatin.axisb.com;
        client_max_body_size 50M;

        # Disable server_tokens Directive
        server_tokens off;

        # security HSTS #
        add_header Strict-Transport-Security "max-age=31536000; includeSubdomains; preload";

        # Disable SSL 3 and keep only TLS #
        ssl_protocols TLSv1.2 TLSv1.3;

        # Disable weak cipher suites #
        ssl_ciphers "EECDH+ECDSA+AESGCM EECDH+aRSA+AESGCM EECDH+ECDSA+SHA384 EECDH+ECDSA+SHA256 EECDH+aRSA+SHA384 EECDH+aRSA+SHA256 EECDH+aRSA+RC4 EECDH EDH+aRSA HIGH !RC4 !aNULL !eNULL !LOW !3DES !MD5 !EXP !PSK !SRP !DSS";

        # Disable unwanted HTTP methods #
        if ($request_method !~ ^(GET|HEAD|POST)$ )
        {
         return 405;
        }

        # Deny http_user_agent - case insensitive matching #
        if ($http_user_agent ~* (netcrawl|npbot|malicious|bot|backdoor|crawler|bandit)) {
            return 403;
        }

        # Security Headers #
        add_header X-XSS-Protection "1; mode=block";                # X-XSS Protection
        add_header X-Frame-Options "SAMEORIGIN";                    # Clickjacking Attack

        # Implement HTTPOnly and Secure Cookie #
        proxy_cookie_path / "/; HTTPOnly; Secure";


        # Set Buffer Size Limitations #
        client_body_buffer_size 1K;
        client_header_buffer_size 1k;
        large_client_header_buffers 2 1k;

        access_log /dev/stdout;
        error_log /dev/stdout;
        location / {
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header Host $http_host;
          proxy_redirect off;
          proxy_pass http://frontend-app:34160;
        }

        location ~* \.(jpg|png|gif|jpe?g)$ {
          valid_referers none blocked digicorpuatin.axisb.com www.digicorpuatin.axisb.com;
          if ($invalid_referer) {
            return 403;
        }
        }
      }

    }
