apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf-be-pv
  namespace: deploy
data:
  nginx.conf: |
    user nginx;
    worker_processes  1;
    error_log  /dev/stdout;
    events {
      worker_connections  10240;
    }
    http {

      access_log  /dev/stdout;
      server {
        listen 80;
        server_name devpaysrvcs.axisb.com;
        client_max_body_size 50M;
        #  Hack to enforce SSL.

        if ($http_x_forwarded_proto != "https") {
          return 301 https://$host$request_uri;
        }

        access_log /dev/stdout;
        error_log /dev/stdout;
        location / {
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header Host $http_host;
          proxy_redirect off;
          proxy_pass http://payvantage:5001;
        }
      }

    }