apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-be-pv
  name: nginx-be-pv
  namespace: deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-be-pv
  template:
    metadata:
      labels:
        app: nginx-be-pv
    spec:
      serviceAccountName: deploy-acc
      containers:
      - image: artifactory.axisb.com/corpomni-frontend-docker-local/devops/nginx:latest
        command: ["nginx", "-g", "daemon off;"]
        imagePullPolicy: Always
        resources:
          requests:
            memory: "256Mi"
            cpu: "256m"
          limits:
            memory: "512Mi"
            cpu: "512m"
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          name: nginx-conf
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf-be-pv
          items:
            - key: nginx.conf
              path: nginx.conf
      imagePullSecrets:
      - name: regcred