apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.config.configmap }}"
  labels:
    namespace: "{{ .Values.namespace }}"
{{- if eq .Values.namespace "deploy-qa" }}
data: 
  .env.local: |
    API_BASE_URL=https://qacdsrvcs.axisb.com
    HOSTNAME=https://qacdsrvcs.axisb.com:443
    NEXT_PUBLIC_API_BASE_URL=https://qacdsrvcs.axisb.com:443
    PORT=443
    API_TIMEOUT=60000
    NEXT_PUBLIC_API_CLIENT_ID=a3089075b2101c2ab2ca33820966a5fb
    NEXT_PUBLIC_API_CLIENT_SECRET=3d48611e7f9974ef6f3e9c73a0cf131c
    NEXT_PUBLIC_BANK_ID=211
    NEXT_PUBLIC_CORP_ID=AVFDIPL
    NEXT_PUBLIC_USER_ID=MAKER1
    NEXT_PUBLIC_STATE_MODE=N
    NEXT_PUBLIC_ACCESS_CODE=dummy
    NODE_TLS_REJECT_UNAUTHORIZED=0
    NEXT_PUBLIC_ENVIRONMENT=QA
    NEXT_PUBLIC_RSA_KEY=-----BEGIN CERTIFICATE-----\nMIIELzCCAxegAwIBAgIIArnMylZGlBgwDQYJKoZIhvcNAQELBQAwaTELMAkGA1UE\nBhMCSU4xFDASBgNVBAgMC01haGFyYXNodHJhMQ8wDQYDVQQHDAZNdW1iYWkxDTAL\nBgNVBAoMBEF4aXMxETAPBgNVBAsMCEF4aXNCYW5rMREwDwYDVQQDDAhBUElHV0JN\nUzAeFw0yMTEwMjYwODQ2MjFaFw0yMzExMTUwODQ2MjFaMGkxCzAJBgNVBAYTAklO\nMRQwEgYDVQQIDAtNYWhhcmFzaHRyYTEPMA0GA1UEBwwGTXVtYmFpMQ0wCwYDVQQK\nDARBeGlzMREwDwYDVQQLDAhBeGlzQmFuazERMA8GA1UEAwwIQVBJR1dCTVMwggEi\nMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDLkALNhDxRPhW3clvfwgf8W2Wq\nkWa/Te4Qkpn+jl/By2m6uu6nf6LBDDDfAbS1tzrn7BntQvowk4gY6umBTEOj9kfu\nTUneWW9O3Qgao+Qe8IUySd92B4fKLtlsg4ugbkYi6YKz+Ab+cbzOZlR6Y8Yhf+JM\nyfNIcj8tErmt3QtTergKtawtwwCr7vkDXSpkxNsmtFWVPBeC8YD9B1/01M7M/8bU\nraVK1SD3ZrgCHi4ppEWbJMPuH0cUqhu1GOZFJyT/s5K5/1GsSbWmXzg4Gw3aZJoH\ncdombtRH7VA5AWCchpxkLXk/QWKAbfb4XL7PwvgCz7eL6HCz00Jg0Wipjhh3AgMB\nAAGjgdowgdcwDAYDVR0TBAUwAwEB/zAdBgNVHQ4EFgQU5JguYg2Bu0pa8zm3/m8C\n+gWCKdIwgZoGA1UdIwSBkjCBj4AU5JguYg2Bu0pa8zm3/m8C+gWCKdKhbaRrMGkx\nCzAJBgNVBAYTAklOMRQwEgYDVQQIDAtNYWhhcmFzaHRyYTEPMA0GA1UEBwwGTXVt\nYmFpMQ0wCwYDVQQKDARBeGlzMREwDwYDVQQLDAhBeGlzQmFuazERMA8GA1UEAwwI\nQVBJR1dCTVOCCAK5zMpWRpQYMAsGA1UdDwQEAwICvDANBgkqhkiG9w0BAQsFAAOC\nAQEAsWnpwN9Pv7jSqOssAfb0UPqiE3q4J2G1M8HK/bjZEESaNmUX3ugBG5tsFLj9\nRIjhxBMqpjzWGTrBhDItFiSecE/bb5a0TuZ3YWENp8MeShfpAkbldxiL2ivYNUL8\nNNIXHm1WFRxcrjKsaUVeEJ7/IFP0r6eSX6Sg3HONWdw+yde0D+VJC5NAkjnmVJhd\neZcQXHuRmmwJWpSXvznewRbV+OhDWyY8MOs5RHqOhpi6IEwmFvdRXC4N5gM7eurp\ndiZWzhJiS5isDSVlx8ogeGLxxY/6wFixGzBS/1a1GMhvkLYylY/81IT7ViyI07QK\nHqlxrbngzQkiAA/ydoXzdMEUQQ==\n-----END CERTIFICATE-----
    NEXT_PUBLIC_LOGOUT_COUNT_DOWN_SECONDS=60
    NEXT_PUBLIC_SESSION_TIMEOUT_IN_SECONDS=300
    NEXT_PUBLIC_SESSION_BUFFER_IN_SECONDS=20
    NEXT_PUBLIC_CDN_URL=https://qadigicorp.axisb.com/
{{- end }}
{{- if eq .Values.namespace "deploy-pprod" }}
data: 
  .env.local: |
    API_BASE_URL=https://rgw.uat.axisb.com/apiconnect-uat/dmz/cdp/api/v1
    HOSTNAME=https://rgw.uat.axisb.com/apiconnect-uat/dmz/cdp/api/v1
    NEXT_PUBLIC_API_BASE_URL=https://rgw.uat.axisb.com/apiconnect-uat/dmz/cdp/api/v1
    NEXT_PUBLIC_API_GATEWAY_URL=https://rgw.uat.axisb.com/
    PORT=443
    API_TIMEOUT=180000
    NEXT_PUBLIC_API_CLIENT_ID=029d0e0faadfc5d79b4a963554fa57b0
    NEXT_PUBLIC_API_CLIENT_SECRET=52cb8031b6bb782d1f1ec75def70a1fb
    NEXT_PUBLIC_BANK_ID=211
    NEXT_PUBLIC_CORP_ID=AVFDIPL
    NEXT_PUBLIC_USER_ID=MAKER1
    NEXT_PUBLIC_STATE_MODE=N
    NEXT_PUBLIC_ACCESS_CODE=dummy
    NEXT_PUBLIC_ENVIRONMENT=PPROD
    NEXT_PUBLIC_RSA_KEY=-----BEGIN CERTIFICATE-----\nMIIELzCCAxegAwIBAgIIArnMylZGlBgwDQYJKoZIhvcNAQELBQAwaTELMAkGA1UE\nBhMCSU4xFDASBgNVBAgMC01haGFyYXNodHJhMQ8wDQYDVQQHDAZNdW1iYWkxDTAL\nBgNVBAoMBEF4aXMxETAPBgNVBAsMCEF4aXNCYW5rMREwDwYDVQQDDAhBUElHV0JN\nUzAeFw0yMTEwMjYwODQ2MjFaFw0yMzExMTUwODQ2MjFaMGkxCzAJBgNVBAYTAklO\nMRQwEgYDVQQIDAtNYWhhcmFzaHRyYTEPMA0GA1UEBwwGTXVtYmFpMQ0wCwYDVQQK\nDARBeGlzMREwDwYDVQQLDAhBeGlzQmFuazERMA8GA1UEAwwIQVBJR1dCTVMwggEi\nMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDLkALNhDxRPhW3clvfwgf8W2Wq\nkWa/Te4Qkpn+jl/By2m6uu6nf6LBDDDfAbS1tzrn7BntQvowk4gY6umBTEOj9kfu\nTUneWW9O3Qgao+Qe8IUySd92B4fKLtlsg4ugbkYi6YKz+Ab+cbzOZlR6Y8Yhf+JM\nyfNIcj8tErmt3QtTergKtawtwwCr7vkDXSpkxNsmtFWVPBeC8YD9B1/01M7M/8bU\nraVK1SD3ZrgCHi4ppEWbJMPuH0cUqhu1GOZFJyT/s5K5/1GsSbWmXzg4Gw3aZJoH\ncdombtRH7VA5AWCchpxkLXk/QWKAbfb4XL7PwvgCz7eL6HCz00Jg0Wipjhh3AgMB\nAAGjgdowgdcwDAYDVR0TBAUwAwEB/zAdBgNVHQ4EFgQU5JguYg2Bu0pa8zm3/m8C\n+gWCKdIwgZoGA1UdIwSBkjCBj4AU5JguYg2Bu0pa8zm3/m8C+gWCKdKhbaRrMGkx\nCzAJBgNVBAYTAklOMRQwEgYDVQQIDAtNYWhhcmFzaHRyYTEPMA0GA1UEBwwGTXVt\nYmFpMQ0wCwYDVQQKDARBeGlzMREwDwYDVQQLDAhBeGlzQmFuazERMA8GA1UEAwwI\nQVBJR1dCTVOCCAK5zMpWRpQYMAsGA1UdDwQEAwICvDANBgkqhkiG9w0BAQsFAAOC\nAQEAsWnpwN9Pv7jSqOssAfb0UPqiE3q4J2G1M8HK/bjZEESaNmUX3ugBG5tsFLj9\nRIjhxBMqpjzWGTrBhDItFiSecE/bb5a0TuZ3YWENp8MeShfpAkbldxiL2ivYNUL8\nNNIXHm1WFRxcrjKsaUVeEJ7/IFP0r6eSX6Sg3HONWdw+yde0D+VJC5NAkjnmVJhd\neZcQXHuRmmwJWpSXvznewRbV+OhDWyY8MOs5RHqOhpi6IEwmFvdRXC4N5gM7eurp\ndiZWzhJiS5isDSVlx8ogeGLxxY/6wFixGzBS/1a1GMhvkLYylY/81IT7ViyI07QK\nHqlxrbngzQkiAA/ydoXzdMEUQQ==\n-----END CERTIFICATE-----
    NODE_TLS_REJECT_UNAUTHORIZED=0
    NEXT_PUBLIC_LOGOUT_COUNT_DOWN_SECONDS=60
    NEXT_PUBLIC_SESSION_TIMEOUT_IN_SECONDS=300
    NEXT_PUBLIC_SESSION_BUFFER_IN_SECONDS=20
    NEXT_PUBLIC_CDN_URL=https://uatgtb.axisb.com/
{{- end }}
{{- if eq .Values.namespace "deploy-uat" }}
data:
  .env.local: |
      API_BASE_URL=https://rgw.uat.axisb.com/apiconnect-uat/uat/cdp/api/v1
      HOSTNAME=https://rgw.uat.axisb.com/apiconnect-uat/uat/cdp/api/v1
      NEXT_PUBLIC_API_BASE_URL=https://rgw.uat.axisb.com/apiconnect-uat/uat/cdp/api/v1
      NEXT_PUBLIC_API_GATEWAY_URL=https://rgw.uat.axisb.com/
      PORT=443
      API_TIMEOUT=180000
      NEXT_PUBLIC_API_CLIENT_ID=367e9c0848e7a686c1026aa9a504414f
      NEXT_PUBLIC_API_CLIENT_SECRET=777cd2ac7a45365bf3d01071f85426a3
      NEXT_PUBLIC_BANK_ID=211
      NEXT_PUBLIC_CORP_ID=AVFDIPL
      NEXT_PUBLIC_USER_ID=MAKER1
      NEXT_PUBLIC_STATE_MODE=N
      NEXT_PUBLIC_ACCESS_CODE=dummy
      NEXT_PUBLIC_ENVIRONMENT=UAT
      NEXT_PUBLIC_RSA_KEY=-----BEGIN CERTIFICATE-----\nMIIELzCCAxegAwIBAgIIArnMylZGlBgwDQYJKoZIhvcNAQELBQAwaTELMAkGA1UE\nBhMCSU4xFDASBgNVBAgMC01haGFyYXNodHJhMQ8wDQYDVQQHDAZNdW1iYWkxDTAL\nBgNVBAoMBEF4aXMxETAPBgNVBAsMCEF4aXNCYW5rMREwDwYDVQQDDAhBUElHV0JN\nUzAeFw0yMTEwMjYwODQ2MjFaFw0yMzExMTUwODQ2MjFaMGkxCzAJBgNVBAYTAklO\nMRQwEgYDVQQIDAtNYWhhcmFzaHRyYTEPMA0GA1UEBwwGTXVtYmFpMQ0wCwYDVQQK\nDARBeGlzMREwDwYDVQQLDAhBeGlzQmFuazERMA8GA1UEAwwIQVBJR1dCTVMwggEi\nMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDLkALNhDxRPhW3clvfwgf8W2Wq\nkWa/Te4Qkpn+jl/By2m6uu6nf6LBDDDfAbS1tzrn7BntQvowk4gY6umBTEOj9kfu\nTUneWW9O3Qgao+Qe8IUySd92B4fKLtlsg4ugbkYi6YKz+Ab+cbzOZlR6Y8Yhf+JM\nyfNIcj8tErmt3QtTergKtawtwwCr7vkDXSpkxNsmtFWVPBeC8YD9B1/01M7M/8bU\nraVK1SD3ZrgCHi4ppEWbJMPuH0cUqhu1GOZFJyT/s5K5/1GsSbWmXzg4Gw3aZJoH\ncdombtRH7VA5AWCchpxkLXk/QWKAbfb4XL7PwvgCz7eL6HCz00Jg0Wipjhh3AgMB\nAAGjgdowgdcwDAYDVR0TBAUwAwEB/zAdBgNVHQ4EFgQU5JguYg2Bu0pa8zm3/m8C\n+gWCKdIwgZoGA1UdIwSBkjCBj4AU5JguYg2Bu0pa8zm3/m8C+gWCKdKhbaRrMGkx\nCzAJBgNVBAYTAklOMRQwEgYDVQQIDAtNYWhhcmFzaHRyYTEPMA0GA1UEBwwGTXVt\nYmFpMQ0wCwYDVQQKDARBeGlzMREwDwYDVQQLDAhBeGlzQmFuazERMA8GA1UEAwwI\nQVBJR1dCTVOCCAK5zMpWRpQYMAsGA1UdDwQEAwICvDANBgkqhkiG9w0BAQsFAAOC\nAQEAsWnpwN9Pv7jSqOssAfb0UPqiE3q4J2G1M8HK/bjZEESaNmUX3ugBG5tsFLj9\nRIjhxBMqpjzWGTrBhDItFiSecE/bb5a0TuZ3YWENp8MeShfpAkbldxiL2ivYNUL8\nNNIXHm1WFRxcrjKsaUVeEJ7/IFP0r6eSX6Sg3HONWdw+yde0D+VJC5NAkjnmVJhd\neZcQXHuRmmwJWpSXvznewRbV+OhDWyY8MOs5RHqOhpi6IEwmFvdRXC4N5gM7eurp\ndiZWzhJiS5isDSVlx8ogeGLxxY/6wFixGzBS/1a1GMhvkLYylY/81IT7ViyI07QK\nHqlxrbngzQkiAA/ydoXzdMEUQQ==\n-----END CERTIFICATE-----
      NODE_TLS_REJECT_UNAUTHORIZED=0
      NEXT_PUBLIC_LOGOUT_COUNT_DOWN_SECONDS=60
      NEXT_PUBLIC_SESSION_TIMEOUT_IN_SECONDS=300
      NEXT_PUBLIC_SESSION_BUFFER_IN_SECONDS=20
      NEXT_PUBLIC_CDN_URL=https://uatdigicorp.axisb.com/
{{- end }}
{{- if eq .Values.namespace "deploy-prod" }}
data:
  .env.local: |
      API_BASE_URL=https://openbanking4.axisbank.com/axis/dmz/cdp/api/v1
      HOSTNAME=https://openbanking4.axisbank.com/axis/dmz/cdp/api/v1
      NEXT_PUBLIC_API_BASE_URL=https://openbanking4.axisbank.com/axis/dmz/cdp/api/v1
      NEXT_PUBLIC_API_GATEWAY_URL=https://openbanking4.axisbank.com
      PORT=443
      API_TIMEOUT=180000
      NEXT_PUBLIC_API_CLIENT_ID=5641cd75ed14005f8e7ba5699338b338
      NEXT_PUBLIC_API_CLIENT_SECRET=fb52e08cf8d4b430e34e92d27c6cc125
      NEXT_PUBLIC_BANK_ID=211
      NEXT_PUBLIC_CORP_ID=AVFDIPL
      NEXT_PUBLIC_USER_ID=MAKER1
      NEXT_PUBLIC_STATE_MODE=N
      NEXT_PUBLIC_ACCESS_CODE=dummy
      NEXT_PUBLIC_ENVIRONMENT=PROD
      NEXT_PUBLIC_RSA_KEY=-----BEGIN CERTIFICATE-----\nMIIDfjCCAmagAwIBAgIIfDAwN3YtxhswDQYJKoZIhvcNAQELBQAwLzELMAkGA1UE\nBhMCSW4xETAPBgNVBAoMCEF4aXNiYW5rMQ0wCwYDVQQDDARBeGlzMB4XDTIyMDEy\nNzA2MzkyNloXDTIzMDEyNzA2MzkyNlowLzELMAkGA1UEBhMCSW4xETAPBgNVBAoM\nCEF4aXNiYW5rMQ0wCwYDVQQDDARBeGlzMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A\nMIIBCgKCAQEAy9MhyQnXCPLjCHt7zoe+FkicYA9BswhtFQ9bImxZ0V+x9CLSBt8a\nj3LwYV4Vu7lqdkbDUTLAUfszbCcSpEuBVQICb7rehikBI+OqM/NwDCmkjbXJkUJc\nMB7erz94WJRrYUyZOuAHeLoSaSvL55VN4qn+QOFwfMEa8L8BOH6SrsyxH0GapOQU\nsZ8NgfLSGCqqwPwB3BAjcm19Yo1e93dQ8xK23zMfNHlg8bXY53KYaRyFV9wu9Cgd\noQJxfAwDE3o8Txbl6eC6eLikrWMQh4l/oXyt4nx4XBrqlCpyKTLZK0AuIXkk4zWU\nL0U2pIOH0G8pQUjnYHeFs6EjKvfddFawhwIDAQABo4GdMIGaMAwGA1UdEwQFMAMB\nAf8wHQYDVR0OBBYEFJmB9HbLu+OC/g4qH25rNhF5pVWdMF4GA1UdIwRXMFWAFJmB\n9HbLu+OC/g4qH25rNhF5pVWdoTOkMTAvMQswCQYDVQQGEwJJbjERMA8GA1UECgwI\nQXhpc2JhbmsxDTALBgNVBAMMBEF4aXOCCHwwMDd2LcYbMAsGA1UdDwQEAwICvDAN\nBgkqhkiG9w0BAQsFAAOCAQEAeGqy2KYJaA+CIWEbkGpWbIIk+//nqeVy4kllSRgV\nW4pHtXaI1doRchEl6UfNxjeAyT2A0UdgsSANJMaW2tE/VElDKSlmHpI7ZvP8ybHn\nD5zhLhb7C7h0VXFyVPoIBbXy83hzQdeTbdgUyjUZW6NSj6o12oh/JBZHJoCC26WA\nur67QKmueqoYchRfnbSYIqre7ZiA/oEDUuHZeY3h5QzW9eXzkphY7ghB+BhI0eDy\neOVzsgq2RYTCy42g6NZPe/62ricIgWHlb5uB7W7M4cFY0ncVcW3+mpHGbMSvylkL\nG9TbQ/Y2s0J/MLr0M6uwvD/VbRo0yvt5XvMuvuY6nYmNWQ==\n-----END CERTIFICATE-----
      NODE_TLS_REJECT_UNAUTHORIZED=0
      NEXT_PUBLIC_AG_GRID_KEY="CompanyName=SoftwareONE India Pvt. Ltd._on_behalf_of_Axis Bank Limited,LicensedApplication=Corporate Digital,LicenseType=SingleApplication,LicensedConcurrentDeveloperCount=20,LicensedProductionInstancesCount=2,AssetReference=AG-025806,ExpiryDate=23_February_2023_[v2]_MTY3NzExMDQwMDAwMA==9009061254e065086548811019114b52"
      NEXT_PUBLIC_LOGOUT_COUNT_DOWN_SECONDS=60
      NEXT_PUBLIC_SESSION_TIMEOUT_IN_SECONDS=300
      NEXT_PUBLIC_SESSION_BUFFER_IN_SECONDS=20
      NEXT_PUBLIC_CDN_URL=https://gtb.axisbank.com/
{{-end }}
