{{- if .Values.vault.exists }}{{- if .Values.postgres }}{{- if .Values.redis }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.config.secret }}"
  labels:
    namespace: "{{ .Values.namespace }}"
type: Opaque
data:
  DB_HOST: "{{ .Values.postgres.host }}"
  DB_PORT: "{{ .Values.postgres.port }}"
  DB_USERNAME: "{{ .Values.postgres.username }}"
  DB_PASSWORD: "{{ .Values.postgres.password }}"
  DB_DATABASE: "{{ .Values.postgres.db }}"
  DB_DATABASE2: "{{ .Values.postgres.db2 }}"
  REDIS_PORT: "{{ .Values.redis.queue.port }}"
  REDIS_HOST: "{{ .Values.redis.queue.host }}"
  REDIS_AUTH_PORT: "{{ .Values.redis.auth.port }}"
  REDIS_AUTH_HOST: "{{ .Values.redis.auth.host }}"
{{- end }}{{- end }}{{- end }}


