apiVersion: v1
kind: ConfigMap
metadata:
  name: corpomni-fe-cm
  labels:
    namespace: deploy
data:
  API_BASE_URL: "https://devcdsrvcs.axisb.com"
  HOSTNAME: "https://devcdsrvcs.axisb.com:443"
  NEXT_PUBLIC_API_BASE_URL: "https://devcdsrvcs.axisb.com:443"
  PORT: "443"
  API_TIMEOUT: "180000"
  NEXT_PUBLIC_BANK_ID: "211"
  NEXT_PUBLIC_CORP_ID: "AVFDIPL"
  NEXT_PUBLIC_USER_ID: "MAKER1"
  NEXT_PUBLIC_STATE_MODE: "N"
  NEXT_PUBLIC_ACCESS_CODE: "dummy"