apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf-be
  namespace: deploy-qa-istio
data:
  nginx.conf: |
    user nginx;
    worker_processes  1;
    error_log  /dev/stdout;
    events {
      worker_connections  10240;
    }
    http {

      access_log  /dev/stdout;
      server {
        listen 80;
        server_name qacdsrvcs.axisb.com;
        client_max_body_size 50M;

        # SSL Protocol #
        ssl_protocols TLSv1.2;

        # security HSTS #
        add_header Strict-Transport-Security "max-age=31536000; includeSubdomains; preload";

        # Httpoxy vulnerability #
        proxy_set_header Proxy "";

        # Request URL overwrite #
        proxy_set_header X-Original-URL "";
        proxy_set_header X-Rewrite-URL "";

        # Prevent Information leaks #
        proxy_hide_header X-Powered-By;
        proxy_hide_header Server;
        proxy_hide_header X-AspNetMvc-Version;
        proxy_hide_header X-AspNet-Version;
        
        # Hack to enforce SSL.
        if ($http_x_forwarded_proto != "https") {
          return 301 https://$host$request_uri;
        }

        access_log /dev/stdout;
        error_log /dev/stdout;
        location / {
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header Host $http_host;
          proxy_redirect off;
          proxy_pass http://coc-client-gateway:15341;
        }

         location /comm-card/ {
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header Host $http_host;
          proxy_redirect off;
          proxy_pass http://coc-client-gateway2:15360;
        }

        location /treasury/ {
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header Host $http_host;
          proxy_redirect off;
          proxy_pass http://coc-client-gateway2:15360;
        }   
        
      }

    }