sa: deploy-prod-acc
namespace: deploy-prod
spec:
  minReplicas: 10
  maxReplicas: 50
  targetCPUUtilizationPercentage: 50
resources:
  requests:
    cpu: 500m
    memory: 500Mi
  limits:
    cpu: 1500m
    memory: 2000Mi
config:
  configmap: corpomni-fe
