apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cache
  labels:
    app: redis-cache
  namespace: deploy-qa-istio
spec:
  selector:
    matchLabels:
      app: redis-cache
      role: master
      tier: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: redis-cache
        role: master
        tier: backend
    spec:
      serviceAccountName: deploy-qa-acc
      containers:
      - name: master
        image: artifactory.axisb.com/corpomni-backend-docker-local/devops/redis/redis:6.2.5-alpine
        resources:
          requests:
            cpu: 250m
            memory: 1000Mi
          limits:            
            memory: 2500Mi
        ports:
        - containerPort: 6379
      imagePullSecrets:
      - name: regcred