apiVersion: v1
kind: Service
metadata:
  name: redis-cache
  labels:
    app: redis-cache
  namespace: deploy-qa-istio
  annotations:
    kubernetes.io/service-account.name: deploy-qa-acc
spec:
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app: redis-cache