apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ngx-web
  name: nginx-app-prod
  namespace: deploy-prod
spec:
  replicas: 10
  selector:
    matchLabels:
      app: ngx-web
  template:
    metadata:
      labels:
        app: ngx-web
    spec:
      serviceAccountName: deploy-prod-acc
      containers:
      - image: artifactory.axisb.com/corpomni-frontend-docker-local/devops/nginx:dmz-prod
        command: ["nginx", "-g", "daemon off;"]
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "2" 
        name: nginx
        ports:
        - containerPort: 443
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          name: nginx-conf
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf-cm
          items:
            - key: nginx.conf
              path: nginx.conf
      imagePullSecrets:
      - name: reg-imgpull-secret
