deployment:
  image: artifactory.axisb.com/corpomni-backend-docker-local/non-prod/coc-client-gateway
  tag: 0.0.2
name: coc-client-gateway
ports: 
  port: 15341
  targetPort: 8080
resources:
  requests:
    memory: 256Mi
    cpu: 2
  limits:
    memory: 2048Mi
    cpu: 2