deployment:
  image: artifactory.axisb.com/corpomni-backend-docker-local/non-prod/payvantage
  tag: 0.0.2
name: payvantage
ports: 
  port: 5001
  targetPort: 5001
resources:
  requests:
    memory: 256Mi
    cpu: 2
  limits:
    memory: 2048Mi
    cpu: 2